class KeyCodes():
    FORWARD_KEY = ord('W')
    LEFT_KEY = ord('A')
    BACKWARD_KEY = ord('S')
    RIGHT_KEY = ord('D')
    WHEEL_MOVEMENT_KEYS = [FORWARD_KEY, LEFT_KEY, BACKWARD_KEY, RIGHT_KEY]

    ARM_EXTEND_KEY = 315 # \
    ARM_RETRACT_KEY = 317 # end
    ARM_MOVEMENT_KEYS = [ARM_EXTEND_KEY, ARM_RETRACT_KEY]

    GRABBER_CLOSE_KEY = 314 # Left Arrow
    GRABBER_OPEN_KEY = 316 # Right Arrow
    GRABBER_MOVEMENT_KEYS = [GRABBER_CLOSE_KEY, GRABBER_OPEN_KEY]


    """  ACTIONS """
    CLEAR_ACTION = ord('/')
    TOGGLE_ACTION_GRABARM_GRAB_OBJECT_KEY = 92 # \
    TOGGLE_ACTION_GRABARM_WEIGH_OBJECT_KEY = 313 # HOME
    TOGGLE_ACTION_GRABARM_DEPOSIT_OBJECT_KEY = 4 # ENTER
    TOGGLE_ACTION_COLLECT_MINERAL_KEY = 77 # m
    TOGGLE_ACTION_KEYS = [CLEAR_ACTION, TOGGLE_ACTION_GRABARM_GRAB_OBJECT_KEY, TOGGLE_ACTION_GRABARM_WEIGH_OBJECT_KEY, TOGGLE_ACTION_GRABARM_DEPOSIT_OBJECT_KEY, 
                        TOGGLE_ACTION_COLLECT_MINERAL_KEY]

    GRABARM_RETRACT_KEY = 3 # Backspace
    RESET_ARM_KEY = 312 # END


    TOGGLE_MANUAL_KEY = ord('T')
    CLEAR_TASK_KEY = 45

    # numbers 0 - 9 on keyboard (manual control)
    SPEED_OPTIONS = [ord(str(key)) for key in range(0,10)]

    """ TASKS """
    # numbers 0 - 9 on keyboard (autonomous control)
    CLEAR_TASK_KEY = 45 # -
    TOGGLE_TASK_SCAN_QR_CODE_KEY = 49 # 1
    TOGGLE_TASK_FIND_CARD_SYMBOL_KEY = 50 # 2
    TOGGLE_TASK_RECOGNIZE_TEMPERATURE_KEY = 51 # 3
    TOGGLE_TASK_DANCING_ON_THE_MOON_KEY = 52 # 4
    TOGGLE_TASK_MOON_SURVIVAL_KEY = 53 # 5
    TOGGLE_TASK_MOON_MAZE_KEY = 54 # 6
    TOGGLE_TASK_MINERAL_ANALYSIS_KEY = 55 # 7
    TOGGLE_TASK_KEYS = [CLEAR_TASK_KEY, TOGGLE_TASK_SCAN_QR_CODE_KEY, TOGGLE_TASK_FIND_CARD_SYMBOL_KEY, 
                        TOGGLE_TASK_RECOGNIZE_TEMPERATURE_KEY, TOGGLE_TASK_DANCING_ON_THE_MOON_KEY,
                        TOGGLE_TASK_MOON_SURVIVAL_KEY, TOGGLE_TASK_MOON_SURVIVAL_KEY,
                        TOGGLE_TASK_MOON_MAZE_KEY, TOGGLE_TASK_MINERAL_ANALYSIS_KEY]
    